language: go
sudo: false
go:
  - 1.5.2
install:
  - go get golang.org/x/tools/cmd/vet
  - go get -v github.com/golang/lint/golint
  - go get -d -t -v ./...
  - go build -v ./...
script:
  - go vet ./...
  - $HOME/gopath/bin/golint .
  - go test -v ./...
